return {
  -- {
  --   "adibhanna/forest-night.nvim",
  --   priority = 1000,
  --   lazy = false,
  --   config = function()
  --     vim.cmd("colorscheme forest-night")
  --   end,
  -- },
  -- {
  --   "wtfox/jellybeans.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     transparent = false,
  --     italics = false,
  --     flat_ui = true, -- toggles "flat UI" for pickers
  --     background = {
  --       dark = "jellybeans",
  --     },
  --     plugins = {
  --       all = false,
  --       auto = true,
  --     },
  --     on_highlights = function(highlights, colors) end,
  --     on_colors = function(colors) end,
  --   },
  -- },
  -- {
  --   "Skardyy/makurai-nvim",
  --   lazy = false,
  --   priority = 1000,
  --   -- config = function()
  --   --   require("jellybeans").setup()
  --   --   vim.cmd.colorscheme("jellybeans")
  --   -- end,
  -- },
  -- {
  --   "slugbyte/lackluster.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   init = function()
  --     local lackluster = require("lackluster")
  --
  --     lackluster.setup({
  --       -- tweak_syntax = {
  --       --   comment = lackluster.color.gray4, -- or gray5
  --       -- },
  --       tweak_background = {
  --         normal = "none",
  --         telescope = "none",
  --         menu = lackluster.color.gray3,
  --         popup = "default",
  --       },
  --     })
  --
  --     -- vim.cmd.colorscheme("lackluster")
  --   end,
  -- },
  -- {
  --   "alligator/accent.vim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("let g:accent_colour = 'blue'")
  --     vim.cmd("let g:accent_no_bg = 1")
  --   end,
  -- },
  -- {
  --   "rebelot/kanagawa.nvim",
  --   opts = {
  --     compile = true,
  --     keywordStyle = { italic = false },
  --     statementStyle = { bold = false },
  --     transparent = true,
  --     colors = { theme = { all = { ui = { bg_gutter = "none" } } } },
  --   },
  -- },
  -- {
  --   "projekt0n/github-nvim-theme",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require("github-theme").setup({
  --       options = {
  --         hide_end_of_buffer = false,
  --         transparent = true,
  --         terminal_colors = true,
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "catppuccin/nvim",
  --   name = "catppuccin",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require("catppuccin").setup({
  --       no_italic = true,
  --       term_colors = true,
  --       transparent_background = true,
  --       show_end_of_buffer = true,
  --       integration_default = false,
  --       integrations = {
  --         cmp = true,
  --         gitsigns = true,
  --         illuminate = { enabled = true },
  --         native_lsp = { enabled = true, inlay_hints = { background = true } },
  --         neogit = true,
  --         semantic_tokens = true,
  --         treesitter = true,
  --         treesitter_context = true,
  --         which_key = true,
  --       },
  --       styles = {
  --         loops = {},
  --         functions = {},
  --         keywords = {},
  --         strings = {},
  --         variables = {},
  --         numbers = {},
  --         booleans = {},
  --         properties = {},
  --         types = {},
  --       },
  --     })
  --   end,
  -- },
}
