return {
	"simrat39/symbols-outline.nvim",
	cmd = { "SymbolsOutline", "SymbolsOutlineOpen" },
	opts = {
		highlight_hovered_item = true,
		show_guides = true,
		auto_preview = false,
		position = "right",
		relative_width = true,
		width = 15,
		auto_close = false,
		show_numbers = false,
		show_relative_numbers = false,
		show_symbol_details = true,
		preview_bg_highlight = "Pmenu",
		autofold_depth = nil,
		auto_unfold_hover = true,
		fold_markers = { "", "" },
		wrap = false,
		keymaps = { -- These keymaps can be a string or a table for multiple keys
			close = { "<Esc>", "q" },
			goto_location = "o",
			focus_location = "<Cr>",
			hover_symbol = "<C-space>",
			toggle_preview = "K",
			rename_symbol = "r",
			code_actions = "a",
			fold = "h",
			unfold = "l",
			fold_all = "W",
			unfold_all = "E",
			fold_reset = "R",
		},
		lsp_blacklist = {},
		symbol_blacklist = {},
		symbols = {
			File = { icon = "file", hl = "TSURI" },
			Module = { icon = "module", hl = "TSNamespace" },
			Namespace = { icon = "NS", hl = "TSNamespace" },
			Package = { icon = "package", hl = "TSNamespace" },
			Class = { icon = "class", hl = "TSType" },
			Method = { icon = "method", hl = "TSMethod" },
			Property = { icon = "prop", hl = "TSMethod" },
			Field = { icon = "field", hl = "TSField" },
			Constructor = { icon = "constr", hl = "TSConstructor" },
			Enum = { icon = "enum", hl = "TSType" },
			Interface = { icon = "interface", hl = "TSType" },
			Function = { icon = "func", hl = "TSFunction" },
			Variable = { icon = "var", hl = "TSConstant" },
			Constant = { icon = "const", hl = "TSConstant" },
			String = { icon = "str", hl = "TSString" },
			Number = { icon = "num", hl = "TSNumber" },
			Boolean = { icon = "bool", hl = "TSBoolean" },
			Array = { icon = "arr", hl = "TSConstant" },
			Object = { icon = "obj", hl = "TSType" },
			Key = { icon = "key", hl = "TSType" },
			Null = { icon = "NULL", hl = "TSType" },
			EnumMember = { icon = "EM", hl = "TSField" },
			Struct = { icon = "struct", hl = "TSType" },
			Event = { icon = "event", hl = "TSType" },
			Operator = { icon = "operator", hl = "TSOperator" },
			TypeParameter = { icon = "TP", hl = "TSParameter" },
		},
	},
}
